# Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json app.js ./
RUN npm install
COPY . ./
ENV UUID=${HOSTNAME}

# Production
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app ./
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
CMD ["npm", "start"]
